/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        engine_ovr: THREE.Mesh;
    };
    materials: {};
};

export function EngineOvr(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/gltf/engine_ovr.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group name='plug_engine' position={[0, 0.01488, -0.35]} rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                    name='engine_ovr'
                    castShadow
                    receiveShadow
                    geometry={nodes.engine_ovr.geometry}
                    material={nodes.engine_ovr.material}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/gltf/engine_ovr.glb');
