/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        ornament_star: THREE.Mesh;
    };
    materials: {};
};

export function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/gltf/ornament_star.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group name='plug_ornament' position={[0, 0.014881, 0.449956]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    name='ornament_star'
                    castShadow
                    receiveShadow
                    geometry={nodes.ornament_star.geometry}
                    material={nodes.ornament_star.material}
                    rotation={[0, -1.570376, 0]}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/gltf/ornament_star.glb');
